version: '2'
services:
  koa_ex.mongo:
    image: tutum/mongodb:3.0
    ports:
      - '27017:27017'
      - '28017:28017'
    restart: always
    volumes:
      - koa_ex_db:/data/db
    env_file:
      - ./variables.env
volumes:
  koa_ex_db:
